<template>
  <div>
    <v-content>
      <v-container
        class="fill-height"
        fluid
      >
        <v-row
          align="center"
          justify="center"
        >
          Профиль
        </v-row>
      </v-container>
    </v-content>
  </div>
</template>